main:
  - identifier: about
    name: About
    url: /about
    weight: 100
  - identifier: contact
    name: Contact
    url: /contact
    weight: 200
  - identifier: news
    name: News 
    url: /news
    weight: 300
  - identifier: blog 
    name: Blog 
    url: /blog 
    weight: 400
